### ISSUE TITLE
Stats Module displaying false stats

### ISSUE THREAD

**Issue by eebs** [modolabs/Kurogo-Mobile-Web#18]
The stats module is reporting the stats incorrectly. I cleared all the stats data from the database, and  after letting it gather some data for a few days, it is showing more page views for 'Year' and '3 Years' than it is for 'Week' and '12  Weeks'. I haven't had time to find a cause, but if I do I'll post back.

This behavior can be viewed here: http://www.eebs-tech.com/stats/

**Comment by akinspe** [comment]
I have a theory, but in order to validate I might need the data that gets stored in the database table. If you're using the basic SQlite database, could you send that to pete.akins@modolabs.com. I think it's related to some old code that was not daylight savings safe. 

Also you need to also remove the log files in addition to removing the data from the stats database to clear everything out.

**Comment by akinspe** [comment]
Ok nevermind. I have changed my theory and it shouldn't require you sending anything. I believe what you are seeing is that the Week and 12-week views do not include the current day, but the code for the year and 3 years would (improperly) include the current day. The difference you are seeing should be the number of requests for the current day. We will alter the reporting system to only include stats up the previous day so there isn't a discrepancy.
