### ISSUE TITLE
Map Search results in catchable error

### ISSUE THREAD

**Issue by eebs** [modolabs/Kurogo-Mobile-Web#38]
I'm running into a problem when searching through the map module. If I search for something, I get an error saying "Argument 1 passed to MapDataController::featureMatchesTokens() must be an instance of MapFeature". Line 41 of MapDataController. Only problem is, MapFeature doesn't exist anywhere in the code base (that I could find with grep). This is on our dev site, which is up to date with the most recent commits. 

I found MapFeature on our live site, so I guess it's just something left over from some old code.

**Comment by sonya** [comment]
Thanks for catching that Eebs. The MapFeature interface was renamed to Placemark awhile ago and I really thought I had found all references to the old name in the code, but apparently not that one. I fixed this in the latest push -- can you see if that helps?

**Comment by eebs** [comment]
Just pulled, it doesn't throw the error any more, thank you. However if there is only one result, instead of going directly to that result, it displays the result list with one item. You can see this if you go here: http://m-dev.uvm.edu/map/ and search for "Williams".

**Comment by eebs** [comment]
I'm also noticing that it is not centered on the placemark. Clicking the center icon does center it however.

**Comment by sonya** [comment]
Thanks. I am closing this issue as the particular problem specified by the title is fixed.

The reason the single result still shows up in a list view is because there is now an option to use Google Places as the map module search engine, but when doing so, Google requires that you display their logo alongside the search results. There are certainly better ways to address this than require that all searches display in a list regardless of search engine, but I just haven't gotten around to it.

The placemark looks centered in my browser. Would you mind pinging me (sonya.huang@modolabs.com) with more details about what device/browser you're seeing the centering problem in?
