### ISSUE TITLE
Remote HTML

### ISSUE THREAD

**Issue by bpayst** [modolabs/Kurogo-Mobile-Web#7]
Remote HTML is not getting pulled into the content module. I have the shipped admissions module configured to pull in a test remote HTML page:

```
TITLE = "ITS Labs"
SUBTITLE = "" 
SHOW_TITLE = 1
CONTENT_TYPE = "html_url"
BASE_URL = "http://activitv.unc.edu/test.html"
HTML_ID = ""
```

and nothing appears. Can't seem to find an error and curl on the server can retrieve the page fine

**Comment by akinspe** [comment]
The issue should fix the blank page, however you really should include an HTML id, otherwise it is pulling the entire HTML (and thus include extra html and body tags which would be invalid).You probably only want to include a certain portion of the page.

**Comment by bpayst** [comment]
I tried it with an HTML_ID as well and couldn't get it to work, this is a simple test page I constructed for troubleshooting. Here's the production config I want to use, which also returns a blank page:

```
[labs]
TITLE = "ITS Labs"
SUBTITLE = ""
SHOW_TITLE = 1
CONTENT_TYPE = "html_url"
BASE_URL = "http://hotline.unc.edu/index.cfm?fuseaction=status.LabOpenSeatInfo" 
HTML_ID = "<table>"
```

**Comment by akinspe** [comment]
<table> is not an html ID. IDs are found in the id attribute of HTML tags. It appears that this feed does not have any ids attached to it. I have added the ability to retrieve the contents via HTML tag. You can choose "body" to include the entire document (sans html,head and body tags) or in this case you could use "table" (without the < >). This should be fixed in the most recent master and the admin console should be updated to illustrate the new property.

**Comment by bpayst** [comment]
ah, I misunderstood the terminology you were using. That new functionality is very useful, though. I had made a module to do that for the old MIT code and it was quite handy.
